import { Router } from "express";
import { getExams } from "../controllers/exams/getExams";
import { addExam } from "../controllers/exams/addExam";
import { deleteExam } from "../controllers/exams/deleteExam";
import { updateExam } from "../controllers/exams/updateExam";
import { uploadConclusion } from "../controllers/exams/uploadConclusion";
import upload from "../middlewares/upload";
import { getConclusion } from "../controllers/exams/getConclusions";
const examRouter = Router();
examRouter.get("/", getExams);
examRouter.post("/addExam", addExam);
examRouter.delete("/deleteExam", deleteExam);
examRouter.put("/updateExam", updateExam);
examRouter.post("/uploadConclusion", upload.single("file"), uploadConclusion);
examRouter.post("/getConclusion", getConclusion);
export default examRouter;
