import { Router } from "express";
import { addSubjects } from "../controllers/schoolSubjects/addSubjects";
import { getSubjects } from "../controllers/schoolSubjects/getSubjects";
import { deleteSubjects } from "../controllers/schoolSubjects/deleteSubject";
import { caculateScoreSubjects } from "../controllers/schoolSubjects/caculateScoreSubjects";
import { verifyToken } from "../middlewares/verifyToken";
const schoolSubjectRouter = Router();
schoolSubjectRouter.post("/addSubjects", addSubjects);
schoolSubjectRouter.get("/getSubjects", getSubjects);
schoolSubjectRouter.delete("/deleteSubjects", deleteSubjects);
schoolSubjectRouter.post("/caculateScore", caculateScoreSubjects);
export default schoolSubjectRouter;
